### ISSUE TITLE
jay's AI

### ISSUE THREAD

**Issue by dhelle2** [dhelle2/Level0#17]
could be following an avatar

**Comment by dhelle2** [comment]
probably use navmesh to have drones follow and perhaps dissapear when they reach player avatars


as *distraction* - so not too fast, not too great a distraction. (also see readme)

**Comment by dhelle2** [comment]
(also see survivor shooter tutorial for navmesh example of following player character)

**Comment by dhelle2** [comment]
(see in particular survivor shooter 4 of 10 tutorial: https://www.youtube.com/watch?v=xUl-Agx2cLc or find pdf of slides on unity web site or through unity by downloading the tutorial)

**Comment by jpatell97** [comment]
complete
