### ISSUE TITLE
slides (less than 5 min presentation

### ISSUE THREAD

**Issue by dhelle2** [dhelle2/Level0#52]
Each team must prepare a formal game presentation (5 minutes per team). The presentation must include:

A slide deck with at least two slides, one stating the name of your project and the names of team members, and one stating what you learned from this team experience
A mandatory narrated, at most 5 minute videoclip (starting with your names and “this is coursework done in CS426, the Dept of CS, University of Illinois at Chicago”). The narration should touch on the following points: team, design, physics, AI, sounds, shaders

(put slides in cs426slidesandvideo folder when done)

**Comment by jpatell97** [comment]
done

**Comment by dhelle2** [comment]
todo: submit (adding myself as assignee)
